<%@page import="org.json.JSONObject"%>
<%@page import="java.util.List"%>
<%@page import="java.util.ArrayList"%>
<%@page import="java.util.HashMap"%>
<%@page import="java.util.Map"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
	
<%
	LinkedHashMap<String, String> fieldList = new LinkedHashMap<>();		
	
	fieldList.put("userName"," {\n\"type\": \"text\",\n\"id\": \"userName\",\n\"name\": \"userName\",\n\"label\": \"User Name\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your name\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");
	fieldList.put("subject"," {\n\"type\": \"text\",\n\"id\": \"subject\",\n\"name\": \"subject\",\n\"label\": \"Subject\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter subject\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("fileNo"," {\n\"type\": \"text\",\n\"id\": \"fileNo\",\n\"name\": \"fileNo\",\n\"label\": \"File Number\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter file number\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("remarks"," {\n\"type\": \"text\",\n\"id\": \"remarks\",\n\"name\": \"remarks\",\n\"label\": \"Remarks\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter Last Last\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("reference"," {\n\"type\": \"text\",\n\"id\": \"reference\",\n\"name\": \"reference\",\n\"label\": \"Reference\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter Last Last\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("currentUser",  "{\n\"type\": \"text\",\n\"id\": \"currentUser\",\n\"name\": \"currentUser\",\n\"label\": \"Current User\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter current user \",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("currentState",	"{\n\"type\": \"text\",\n\"id\": \"currentState\",\n\"name\": \"currentState\",\n\"label\": \"Current State\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter current state\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("year",        	" {\n\"type\": \"text\",\n\"id\": \"year\",\n\"name\": \"year\",\n\"label\": \" Year\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"year\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"4\"\n            }\n        }");	
	fieldList.put("dealingOrganizationId"," {\n\"type\": \"text\",\n\"id\": \"dealingOrganizationId\",\n\"name\": \"dealingOrganizationId\",\n\"label\": \" Dealing Organization\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter dealing organization  \",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("groupId",			" {\n\"type\": \"text\",\n\"id\": \"groupId\",\n\"name\": \"groupId\",\n\"label\": \"GroupId\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter groupId\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("companyId",			" {\n\"type\": \"text\",\n\"id\": \"companyId\",\n\"name\": \"companyId\",\n\"label\": \"CompanyId\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter companyId\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("userId",				" {\n\"type\": \"text\",\n\"id\": \"userId\",\n\"name\": \"userId\",\n\"label\": \" UserId\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter userId\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	
	
	fieldList.put("createDate",			" {\n \"type\":\"date\",\n  \"id\":\"createDate\",\n \"name\":\"createDate\",\n            \"classes\":\"form-control\",\n            \"label\":\"Create Date\",\n            \"placeholder\":\"\",\n            \"suggestion\":\"Please enter the date of creation\",\n            \"config\":{\n                \"hidden\":false,\n                \"disabled\":false,\n                \"readOnly\":false,\n                \"checked\":false\n            },\n            \"value\":\"\",\n            \"htmlElement\":\"date\",                \n            \"errorMessage\":\"\",\n            \"valid\":\"\",\n            \"validation\":{\n                \"required\":true\n               \n            }\n        }");
	fieldList.put("modifiedDate",		" {\n \"type\":\"date\",\n   \"id\":\"modifiedDate\",\n  \"name\":\"modifiedDate\",\n            \"classes\":\"form-control\",\n            \"label\":\"Modified Date\",\n            \"placeholder\":\"\",\n            \"suggestion\":\"Please enter the date of modification\",\n            \"config\":{\n                \"hidden\":false,\n                \"disabled\":false,\n                \"readOnly\":false,\n                \"checked\":false\n            },\n            \"value\":\"\",\n            \"htmlElement\":\"date\",                \n            \"errorMessage\":\"\",\n            \"valid\":\"\",\n            \"validation\":{\n                \"required\":true\n               \n            }\n        }");
	 
	 fieldList.put("type",			" {\n\"type\": \"select\",\n	\"id\": \"type\",\n			\"name\": \"type\",\n			\"label\": \"Type\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select type\",\n            \"suggestion\": \"Select a type from the dropdown\",\n           		 \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n                \"id\": \"\",\n                \"url\": \"\",\n                \"value\": \"\"\n              \n },\n            \"options\": [\n                {\n                    \"label\": \"SFS\",\n                    \"value\": \"SFS\"\n                },\n                {\n                    \"label\": \"NON-SFS\",\n                    \"value\": \"NON-SFS\"\n                }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	 fieldList.put("nature",		" {\n\"type\": \"select\",\n	\"id\": \"nature\",	\n		\"name\": \"nature\",\n			\"label\": \"Nature\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select Nature\",\n            \"suggestion\": \"Select a nature from the dropdown\",\n          	  \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n                \"id\": \"\",\n                \"url\": \"\",\n                \"value\": \"\"\n              \n },\n            \"options\": [\n                {\n                    \"label\": \"Electronic\",\n                    \"value\": \"Electronic\"\n                },\n                {\n      \"label\": \"Physical\",\n                    \"value\": \"Physical\"\n  }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	 fieldList.put("categoryId",	"  {\n\"type\": \"select\",\n	\"id\": \"categoryId\",\n	\"name\": \"categoryId\",\n		\"label\": \"Category\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select category\",\n            \"suggestion\": \"Select a category from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n                \"id\": \"\",\n                \"url\": \"\",\n                \"value\": \"\"\n              \n },\n            \"options\": [\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n                },\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n          }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	 fieldList.put("fileCodeId",	"  {\n\"type\": \"select\",\n	\"id\": \"fileCodeId\",\n	\"name\": \"fileCodeId\",\n		\"label\": \"FileCode\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select file code\",\n            \"suggestion\": \"Select a file code from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n                \"id\": \"\",\n                \"url\": \"\",\n                \"value\": \"\"\n              \n },\n            \"options\": [\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n                },\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n        }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	 fieldList.put("headId",		" {\n\"type\": \"select\",\n	\"id\": \"headId\",\n		\"name\": \"headId\",\n			\"label\": \"Head\",\n            	\"classes\":\"form-control\",\n            \"placeholder\": \"Select head\",\n           	 \"suggestion\": \"Select head from the dropdown\",\n            			\"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n                \"id\": \"\",\n                \"url\": \"\",\n                \"value\": \"\"\n              \n },\n            \"options\": [\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n                },\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n        }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");	
	 fieldList.put("userPostId",	"  {\n\"type\": \"select\",\n	\"id\": \"userPostId\",\n	\"name\": \"userPostId\",\n		\"label\": \"User Post\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select user post\",\n            \"suggestion\": \"Select user post from  the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n                \"id\": \"\",\n                \"url\": \"\",\n                \"value\": \"\"\n              \n },\n            \"options\": [\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n                },\n                {\n                    \"label\": \"code\",\n                    \"value\": \"A\"\n        }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
		
	fieldList.put("submitAction",	" {\n\"type\": \"POST\",\n \"id\": \"save\",\n\"name\": \"save\",\n  \"label\": \"\",\n  \"value\": \"Save\",\n        \"classes\":\"form-control\",\n     \"class\": \"btn btn-primary\", \n  \"url\": \"http://localhost:8081/api/v1/user\", \n           \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n        }");	
	fieldList.put("editAction",		" {\n\"type\": \"PUT\",\n \"id\": \"edit\",\n\"name\": \"edit\",\n  \"label\": \"\",\n    \"value\": \"Edit\",\n      \"classes\":\"form-control\",\n     	\"class\": \"btn btn-primary\", \n   \"url\": \"\", \n    \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n        }");	
	fieldList.put("cancelAction",	" {\n\"type\": \"cancel\",\n \"id\": \"cancel\",\n\"name\": \"cancel\",\n  \"label\": \"\",\n  \"value\": \"Cancel\",\n        \"classes\":\"form-control\",\n     \"class\": \"btn btn-default\",\n        \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n        }");	 
	fieldList.put("posts","  {\n\"type\":\"checkbox\",\n \"value\":\"\",\n\"id\":\" posts\",\n\"name\":\"posts\",\n\"classes\":\"form-check-input\",\n \"checked\":\"checked\",\n\"label\":\"Posts\",\n\"placeholder\":\"\",\n            \"suggestion\":\"Please select the Post\",\n            \"config\":{\n                \"hidden\":false,\n                \"disabled\":false,\n                \"readOnly\":false,\n                \"checked\":false\n            },\n             \"provider\": {\n \"url\": \"https://jsonplaceholder.typicode.com/todos/1\",\n\"id\":\"\",\n \"checked\":\"checked\",\n \"value\":\"false\",\n  \"label\": \" Posts\"\n},\n            \"htmlElement\":\"checkbox\",\n            \"errorMessage\":\"\",\n            \"valid\":\"\",\n            \"validation\":{\n                \"required\":true,\n \"value\":\"\",\n                \"maxLength\":\"\",\n \"checked\":\"checked\",\n                \"minLength\":\"\"\n            }\n        }");
	fieldList.put("Choices"," {\n\"type\":\"radio\",\n\"id\":\"choice\",\n \"name\":\"choice\",\n \"classes\":\"form-check-input\",\n \"label\":\"Choices\",\n \"placeholder\":\"\",\n  \"suggestion\":\"\",\n\"provider\": {\n \"url\": \"https://jsonplaceholder.typicode.com/todos/1\",\n\"value\":\"false\",\n \"id\":\"\",\n\"label\": \"\"\n },\n  \"options\":[]\n}");
	request.setAttribute("formDefinition", fieldList);
%>

 <%@ include file="../form/form-renderer.jsp" %>


	
