<%@page import="org.json.JSONObject"%>
<%@page import="java.util.List"%>
<%@page import="java.util.ArrayList"%>
<%@page import="java.util.HashMap"%>
<%@page import="java.util.Map"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
	
<%
	LinkedHashMap<String, String> fieldList = new LinkedHashMap<>();		
	
	fieldList.put("subject"," {\n\"type\": \"text\",\n\"id\": \"subject\",\n\"name\": \"subject\",\n\"label\": \"Subject\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter subject\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("fileNo"," {\n\"type\": \"text\",\n\"id\": \"fileNo\",\n\"name\": \"fileNo\",\n\"label\": \"File Number\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter file number\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("remarks"," {\n\"type\": \"text\",\n\"id\": \"remarks\",\n\"name\": \"remarks\",\n\"label\": \"Remarks\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter Last Last\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	fieldList.put("reference"," {\n\"type\": \"text\",\n\"id\": \"reference\",\n\"name\": \"reference\",\n\"label\": \"Reference\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter Last Last\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	

	//fieldList.put("userName"," {\n\"type\": \"text\",\n\"id\": \"userName\",\n\"name\": \"userName\",\n\"label\": \"User Name\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter your name\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");
	//fieldList.put("groupId",			" {\n\"type\": \"text\",\n\"id\": \"groupId\",\n\"name\": \"groupId\",\n\"label\": \"GroupId\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter groupId\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	//fieldList.put("companyId",			" {\n\"type\": \"text\",\n\"id\": \"companyId\",\n\"name\": \"companyId\",\n\"label\": \"CompanyId\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter companyId\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	//fieldList.put("userId",				" {\n\"type\": \"text\",\n\"id\": \"userId\",\n\"name\": \"userId\",\n\"label\": \" UserId\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Enter userId\",\n            \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"text\",\n            \"errorMessage\": \"Please Enter The Valid Data\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"20\",\n                \"minLength\": \"3\"\n            }\n        }");	
	
	
	fieldList.put("createDate",			" {\n \"type\":\"date\",	\n  \"id\":\"createDate\",\n \"name\":\"createDate\",\n            \"classes\":\"form-control\",\n            \"label\":\"Create Date\",\n            \"placeholder\":\"\",\n            \"suggestion\":\"Please enter the date of creation\",\n            \"config\":{\n                \"hidden\":false,\n                \"disabled\":false,\n                \"readOnly\":false,\n                \"checked\":false\n            },\n            \"value\":\"\",\n            \"htmlElement\":\"date\",                \n            \"errorMessage\":\"\",\n            \"valid\":\"\",\n            \"validation\":{\n                \"required\":true\n               \n            }\n        }");
	fieldList.put("modifiedDate",		" {\n \"type\":\"date\",	\n   \"id\":\"modifiedDate\",\n  \"name\":\"modifiedDate\",\n            \"classes\":\"form-control\",\n            \"label\":\"Modified Date\",\n            \"placeholder\":\"\",\n            \"suggestion\":\"Please enter the date of modification\",\n            \"config\":{\n                \"hidden\":false,\n                \"disabled\":false,\n                \"readOnly\":false,\n                \"checked\":false\n            },\n            \"value\":\"\",\n            \"htmlElement\":\"date\",                \n            \"errorMessage\":\"\",\n            \"valid\":\"\",\n            \"validation\":{\n                \"required\":true\n               \n            }\n        }");
	 
	//type number
	fieldList.put("year",				"{\n\"type\":\"number\",		\n\"id\":	\"year\",			\n \"name\":\"year\",			\n\"classes\":\"form-control\",	\n\"label\":\"Year\",					\n  \"value\": \"2023\",\n        \"placeholder\":\"Enter Year\",\n         \"suggestion\":\"Please enter year\",\n            			\"config\":	{\n  \"hidden\":false,\n             \"disabled\":true,\n      \"readOnly\":false,\n        \"checked\":false\n     },\n     \n   \"htmlElement\":\"userPost\",    \n            \"errorMessage\":\" please enter  the valid data\",\n            \"valid\":\"\",\n            \"validation\":{\n   \"required\": true,\n    \"maxLength\": \"10\", \n   \"minLength\":\"10\"\n            }\n        }");
	fieldList.put("dealingOrganizationId","{\n\"type\":\"number\",		\n\"id\":\"dealingOrganizationId\",\n \"name\":\"dealingOrganizationId\",		\n\"classes\":\"form-control\",\n\"label\":\"User Post\",\n  \"value\": \"1\",\n         \"placeholder\":\"Enter dealing organization\",\n         \"suggestion\":\"Please enter user post\",\n  \"config\":	{\n  \"hidden\":true,\n             \"disabled\":false,\n      \"readOnly\":false,\n        \"checked\":false\n     },\n     \n   \"htmlElement\":\"userPost\",    \n            \"errorMessage\":\" please enter  the valid data\",\n            \"valid\":\"\",\n            \"validation\":{\n   \"required\": true,\n    \"maxLength\": \"10\", \n   \"minLength\":\"10\"\n            }\n        }"); 
	fieldList.put("currentUser",		"{\n\"type\":\"number\",		\n\"id\":\"currentUser\",			\n\"name\":\"currentUser\",		\n\"classes\":\"form-control\",\n\"label\":\"Current User\",\n  \"value\": \"1\",\n         \"placeholder\":\"Enter current user\",\n                       			\"suggestion\":\"Please enter current user\",\n   \"config\":	{\n  \"hidden\":true,\n             \"disabled\":false,\n      \"readOnly\":false,\n        \"checked\":false\n     },\n     \n   \"htmlElement\":\"currentUser\",    \n            \"errorMessage\":\" please enter  the valid data\",\n            \"valid\":\"\",\n            \"validation\":{\n   \"required\": true,\n    \"maxLength\": \"10\", \n   \"minLength\":\"10\"\n            }\n        }");
	fieldList.put("userPostId",			"{\n\"type\":\"number\",		\n\"id\":\"userPostId\",			\n \"name\":\"userPostId\",		\n\"classes\":\"form-control\",\n\"label\":\"User Post\",\n  \"value\": \"1\",\n         \"placeholder\":\"Enter user post\",\n         \"suggestion\":\"Please enter user post\",\n            			\"config\":	{\n  \"hidden\":true,\n             \"disabled\":false,\n      \"readOnly\":false,\n        \"checked\":false\n     },\n     \n   \"htmlElement\":\"userPost\",    \n            \"errorMessage\":\" please enter  the valid data\",\n            \"valid\":\"\",\n            \"validation\":{\n   \"required\": true,\n    \"maxLength\": \"10\", \n   \"minLength\":\"10\"\n            }\n        }");
	
	//type select options			
	fieldList.put("type", " {\n \"type\":\"select\",	\n \t \"selected\" :\"\",\n            \"id\": \"type\",\n            \"name\": \"type\",\n            \"label\": \"Type\",\n           \"classes\":\"form-control\",\n          \"placeholder\": \"Select Type\",\n        \"suggestion\": \"Select a type from the dropdown\",\n            \"config\": {\n    \"disabled\": false,\n       \"readOnly\": false,\n      \"checked\": false,\n        \"hidden\": false\n       },\n     \"provider\": {\n   \t \"id\" :\"type\",\n       \t \"type\" :\"GET\",\n      \t \"url\":\"\",\n       \t \"selected\" :\"selected\",\n     	\t \"value\":\"\",\n        \t \"params\":[]\n    },\n      \"options\": [\n  {\n  \"label\": \"SFS\",\n         \"value\": \"SFS\"\n         },\n     {\n    \"label\": \"NON-SFS\",\n    \"value\": \"NON-SFS\"\n    }\n   ],\n     \"value\": \"\",\n      \"htmlElement\": \"select\",\n      \"errorMessage\": \"\",\n      \"valid\": false,\n    \"validation\": {\n  \"required\": true }\n   }");
	fieldList.put("nature", " {\n \"type\":\"select\",	\n \t \"selected\" :\"\",\n            \"id\": \"nature\",\n            \"name\": \"nature\",\n            \"label\": \"Nature\",\n        \"classes\":\"form-control\",\n        \"placeholder\": \"Select Nature\",\n       \"suggestion\": \"Select a nature from the dropdown\",\n         \"config\": {\n   	\"disabled\": false,\n      \"readOnly\": false,\n       \"checked\": false,\n        \"hidden\": false\n      },\n     \"provider\": {\n   \t \"id\" :\"nature\",\n     \t \"type\" :\"GET\",\n       \t \"url\":\"\",\n      \t \"selected\" :\"selected\",\n       \t \"value\":\"\",\n        \t \"params\":[]\n   },\n       \"options\": [\n  {\n  \"label\": \"Electronic\",\n  \"value\": \"Electronic\"\n  },\n    {\n   \"label\": \"Physical\",\n     \"value\": \"Physical\"\n  }\n   ],\n     \"value\": \"\",\n        \"htmlElement\": \"select\",\n   	\"errorMessage\": \"\",\n      \"valid\": false,\n    \"validation\": {\n  \"required\": true }\n  }");	
	fieldList.put("fileCode", " {\n \"type\":\"select\",\n \t \"selected\" :\"\",\n        		\"id\": \"fileCodeId\",\n        \"name\": \"fileCodeId\",\n         \"label\": \"FileCode\",\n     \"classes\":\"form-control\",\n        \"placeholder\": \"Select fileCode\",\n      \"suggestion\": \"Select a fileCodeId from the dropdown\",\n    \"config\": {\n     \"disabled\": false,\n      \"readOnly\": false,\n       \"checked\": false,\n        \"hidden\": false\n      },\n    \"provider\": {\n   \t \"id\" :\"fileCodeId\",\n   \t \"type\" :\"GET\",\n      \t \"url\":\"\",\n     \t \"selected\" :\"selected\",\n        \t \"value\":\"\",\n        \t \"params\":[]\n  },\n        \"options\": [\n  {\n  \"label\": \"code\",\n        \"value\": \"1\"\n          },\n   {\n   \"label\": \"code\",\n         \"value\": \"2\"\n          }\n   ],\n      \"value\": \"\",\n       \"htmlElement\": \"select\",\n     \"errorMessage\": \"\",\n      \"valid\": false,\n     \"validation\": {\n  \"required\": true }\n }");
	
	//type select dataprovider	
	fieldList.put("category", " {\n \"type\":\"select\",	\n \t \"selected\" :\"\",\n            \"id\": \"categoryId\",\n            \"name\": \"categoryId\",\n            \"label\": \"Category\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select category\",\n            \"suggestion\": \"Select a category from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n              \t \"id\" :\"categoryId\",\n              \t \"type\" :\"GET\",\n              \t \"url\":\"http://localhost:8082/api/v1/jetprocess/category\",\n              \t \"selected\" :\"selected\",\n              \t \"value\":\"\",\n              \t \"params\":[]\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n  \"required\": true }\n        }");
	fieldList.put("basichead", " {\n \"type\":\"select\",	\n \t \"selected\" :\"\",\n            \"id\": \"basicheadId\",\n            \"name\": \"basicheadId\",\n            \"label\": \"Basichead\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select basichead\",\n            \"suggestion\": \"Select a basichead from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n              \t \"id\" :\"basicheadId\",\n              \t \"type\" :\"GET\",\n              \t \"url\":\"http://localhost:8082/api/v1/jetprocess/basichead\",\n              \t \"selected\" :\"selected\",\n              \t \"value\":\"\",\n              \t \"params\":[]\n            },\n            \"options\": [],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n  \"required\": true }\n        }");
	fieldList.put("primaryhead", " {\n \"type\":\"select\",		\n \"id\": \"primaryheadId\",\n            \"name\": \"primaryheadId\",\n            \"label\": \"Primaryhead\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select primaryhead\",\n            \"suggestion\": \"Select a primaryhead from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n              \t \"id\" :\"primaryheadId\",\n              \t  \"type\":\"GET\",\n              \t \"url\":\"http://localhost:8082/api/v1/jetprocess/primaryhead\",\n              \t \"value\":\"\",\n              \t \"params\":[ {\n       \t \t\t\"name\":\"basicheadId\",\n              \t \t\t\"value\":\"#\"}]\n            },\n            \"options\": [\n                {\n                    \"label\": \"United States\",\n                    \"value\": \"USA\"\n                },\n                {\n                    \"label\": \"India\",\n                    \"value\": \"INDIA\"\n                },\n                {\n                    \"label\": \"Canada\",\n                    \"value\": \"CANADA\"\n                }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	fieldList.put("secondaryhead", "{\n \"type\":\"select\",		\n \"id\": \"secondaryheadId\",\n            \"name\": \"secondaryheadId\",\n            \"label\": \"Secondaryhead\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select secondaryhead\",\n            \"suggestion\": \"Select a secondaryhead from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n              \t \"id\" :\"secondaryheadId\",\n              \t  \"type\":\"GET\",\n              \t \"url\":\"http://localhost:8082/api/v1/jetprocess/primaryhead\",\n              \t \"value\":\"\",\n              \t \"params\":[ {\n       \t \t\t\"name\":\"primaryheadId\",\n              \t \t\t\"value\":\"#\"}]\n            },\n            \"options\": [\n                {\n                    \"label\": \"United States\",\n                    \"value\": \"USA\"\n                },\n                {\n                    \"label\": \"India\",\n                    \"value\": \"INDIA\"\n                },\n                {\n                    \"label\": \"Canada\",\n                    \"value\": \"CANADA\"\n                }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	fieldList.put("tertiaryhead", " {\n \"type\":\"select\",		\n \"id\": \"headId\",\n            \"name\": \"headId\",\n            \"label\": \"Tertiaryhead\",\n            \"classes\":\"form-control\",\n            \"placeholder\": \"Select tertiaryheadId\",\n            \"suggestion\": \"Select a tertiaryheadId from the dropdown\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n             \"provider\": {\n              \t \"id\" :\"tertiaryheadId\",\n              \t  \"type\":\"GET\",\n              \t \"url\":\"http://localhost:8082/api/v1/jetprocess/tertiaryhead\",\n              \t \"value\":\"\",\n              \t \"params\":[ {\n       \t \t\t\"name\":\"secondaryheadId\",\n              \t \t\t\"value\":\"#\"}]\n            },\n            \"options\": [\n                {\n                    \"label\": \"United States\",\n                    \"value\": \"USA\"\n                },\n                {\n                    \"label\": \"India\",\n                    \"value\": \"INDIA\"\n                },\n                {\n                    \"label\": \"Canada\",\n                    \"value\": \"CANADA\"\n                }\n            ],\n            \"value\": \"\",\n            \"htmlElement\": \"select\",\n            \"errorMessage\": \"\",\n            \"valid\": false,\n            \"validation\": {\n                \"required\": true,\n                \"maxLength\": \"\",\n                \"minLength\": \"\"\n            }\n        }");
	
	//actions
	fieldList.put("submitAction",	" {\n\"type\": \"POST\",\n \"id\": \"save\",\n\"name\": \"save\",\n  \"label\": \"\",\n  \"value\": \"Save\",\n        \"classes\":\"form-control\",\n     \"class\": \"btn btn-primary\", \n  \"url\": \"http://localhost:8082/api/v1/docFile\", \n           \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n        }");	
	fieldList.put("editAction",		" {\n\"type\": \"PUT\",\n \"id\": \"edit\",\n\"name\": \"edit\",\n  \"label\": \"\",\n    \"value\": \"Edit\",\n      \"classes\":\"form-control\",\n     	\"class\": \"btn btn-primary\", \n   \"url\": \"\", \n    \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n        }");	
	fieldList.put("cancelAction",	" {\n\"type\": \"cancel\",\n \"id\": \"cancel\",\n\"name\": \"cancel\",\n  \"label\": \"\",\n  \"value\": \"Cancel\",\n        \"classes\":\"form-control\",\n     \"class\": \"btn btn-default\",\n        \"suggestion\": \"\",\n            \"config\": {\n                \"disabled\": false,\n                \"readOnly\": false,\n                \"checked\": false,\n                \"hidden\": false\n            },\n        }");	 
	
	request.setAttribute("formDefinition", fieldList);
%>

	<%@ include file="form-renderer.jsp" %>


	
